---
# Services & Solutions
all: 
  - title: 웹 기술 개발 & 컨설팅 
    subtitle: Web Development /w Ruby & Rails
    name: webdev
    link: /web-development/
    icon: <i class="fa fa-rocket" aria-hidden="true"></i>
  - title: 워드프레스 제작 운영
    subtitle: WordPress Development & Consulting
    name: wordpress
    link: /wordpress/
    icon: <i class="fa fa-wordpress" aria-hidden="true"></i>
  - title: 디지털 마케팅 솔루션
    subtitle: Digital Content Marketing Solutions
    name: martech
    link: /marketing-technology/
    icon: <i class="fa fa-line-chart" aria-hidden="true"></i>

# solutions:
#   - title: Pickcle
#     name: pickcle
#     description: 골라 보는 나만의 맞춤 콘텐츠
#     color: '#593196'
#     link: http://pickcle.co/
#   - title: 플라타너스트리
#     name: platanustree
#     description: 책 읽는 좋은 습관! 내 온라인 서재
#     color: '#103210'
#     link: https://platanustree.com/
#   - title: Landing Jekyll
#     name: landing-jekyll
#     description: Jekyll 기반 웹사이트 제작 서비스
#     color: '#FFAA00'
#     link: https://landing-jekyll.usefulparadigm.com/
#   - title: WordPress 가이드
#     name: wpguide
#     description: 워드프레스를 여행하는 히치하이커를 위한 안내서
#     color: '#0B5DD0'
#     link: https://wpguide.usefulparadigm.com/
#   - title: Bayes
#     name: bayes
#     description: 머신러닝 NLP (Coming Soon!)
#     color: '#85144b'
#     link: '#'

webdev:
  publications:
  - title: 레일스와 함께하는 애자일 웹 개발
    url: http://book.naver.com/bookdb/book_detail.nhn?bid=2691152
    cover: https://image.aladin.co.kr/product/88/90/cover/8991268269_1.jpg
    description: 데이브 토머스, 데이비드 하이네마이어 한슨 저 | 김석준 외 2명 역 | 인사이트 | 2007
  - title: 프로그래밍 얼랭
    url: http://book.naver.com/bookdb/book_detail.nhn?bid=4590312
    cover: https://image.aladin.co.kr/product/221/27/letslook/8991268404_f.jpg  
    description: 조 암스트롱 저 | 김석준 역 | 인사이트 | 2008
  - title: Rails Recipes
    url: http://book.naver.com/bookdb/book_detail.nhn?bid=2625095
    cover: https://image.aladin.co.kr/product/87/48/cover/8991268242_1.jpg
    description: 차드 파울러 저 | 김석준 역 | 인사이트 | 2007
  references:
  - title: 플라타너스트리
    url: https://platanustree.com/
    description: 책 읽는 좋은 습관! 내 온라인 서재
    # screenshot: https://usefulparadigm.s3.amazonaws.com/images/2018/Screenshot-platanustree_2018-12-21.jpg
    screenshot: /img/screenshots/platanustree.jpg
  - title: Pickcle
    url: https://pickcle.co/
    description: 골라보는 나만의 맞춤 콘텐츠, 픽클!
    # screenshot: https://usefulparadigm.s3.amazonaws.com/images/2018/Screenshot-pickcle_2018-12-21.jpg
    screenshot: /img/screenshots/pickcle.jpg
        
martech:
  resources:  
    - title: Bottr로 페이스북 메신저 챗봇 만들기
      url: http://bit.ly/2nZ2WSm
      thumb: https://cdn-images-1.medium.com/max/1200/1*7DPF8WAe31qMcap7gUTxlw.jpeg
    - title: 검색엔진최적화(SEO) 쉬운 가이드
      url: http://bit.ly/2oIHKx6
      thumb: https://cdn-images-1.medium.com/max/1600/1*BTZAgsS0q5Ye6S-IcWTINg.jpeg
    - title: Foundation for Emails로 반응형 HTML Email 만들기
      url: http://bit.ly/2oIOZoC
      thumb: https://cdn-images-1.medium.com/max/2000/1*mg9NoZzLpBXdAg7MY6cXmg.png
    - title: 랜딩 페이지에 컨택 폼 추가하기
      url: http://bit.ly/2oILHBY
      thumb: https://cdn-images-1.medium.com/max/2000/1*OO520mXc8fKFGedrWoO1Fg.jpeg
  references:
  - title: Landing Jekyll
    url: https://landing-jekyll.usefulparadigm.com/
    description: 지킬 기반 랜딩페이지 제작 서비스
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2018/Screenshot-landingjekyll_2018-12-21.jpg
    screenshot: /img/screenshots/landing-jekyll.jpg
  - title: Buzzmix
    url: http://buzzmix.co/
    description: 소셜미디어 콘텐츠 큐레이션 솔루션
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2018/Screenshot-buzzmix_2018-12-21.jpg
    screenshot: /img/screenshots/buzzmix.jpg

wordpress:
  resources:
  - title: WordPress 가이드
    url: https://wpguide.usefulparadigm.com/
    thumb: https://usefulpa.s3.amazonaws.com/images/2017/up-ref-wordpress-theme-wpguide.png
  references:
  - title: LG CES2017 Newsroom
    # url: http://ces2017.lgnewsroom.com/
    description: Custom Theme, 반응형웹, 2017
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2017/up-ref-wordpress-theme-lgces2017.png
    screenshot: /img/screenshots/lg-ces2017.jpg
  - title: Computex Taipei 2016 한국, 2016
    # url: http://computextaipei.kr/
    description: Custom Theme, 반응형웹
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2017/up-ref-wordpress-theme-computex2016.png
    screenshot: /img/screenshots/computex-2016.jpg
  - title: 페르노리카 코리아
    # url: http://www.pernod-ricard-korea.com/
    description: Custom Theme, 반응형웹, 2015
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2017/up-ref-wordpress-theme-prk.png
    screenshot: /img/screenshots/pernod-ricard.jpg
  - title: 오스터 코리아 공식몰
    # url: http://www.oster.co.kr/
    description: Custom Theme, WooCommerce, 2014
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2018/screenshot-wp-osterkr.png
    screenshot: /img/screenshots/oster-korea.jpg
  - title: Discover Hyundai
    # url: http://www.discover-hyundai.com/
    description: Custom Theme, 반응형웹, 2013
    # screenshot: https://usefulpa.s3.amazonaws.com/images/2018/screenshot-wp-hqtour.png
    screenshot: /img/screenshots/discover-hyundai.jpg
    